language: scala
scala:
  - "2.11.6"
script:
  - travis_retry sbt clean coverage test
after_success: "sbt coverageReport coveralls"
jdk:
  - oraclejdk8
install:
  - sudo apt-get install build-essential
  - mkdir tmp
  - cd tmp
  - wget http://protobuf.googlecode.com/files/protobuf-2.5.0.tar.gz 
  - tar xzvf protobuf-2.5.0.tar.gz
  - cd protobuf-2.5.0
  - ./configure
  - make
  - make check
  - sudo make install
  - sudo ldconfig
  - protoc --version
  - cd ./../../